### PR TITLE
Issue with an array of arrays query

### LINKED ISSUE #21: error in the console after 1st load
"Uncaught SyntaxError: Unexpected token E in JSON at position 0" this is because of the placeholder text in the query editor

// cc @nickbalestra @chriscartlidge

### LINKED ISSUE #22: query doesn't produce expected result
the following query doesn't produce the expected result (restaurant list in big-mars project)

``` json
[
  [
    "restaurantsById",
    [
      4275,
      85456,
      102474,
      105498,
      108642
    ],
    [
      "id",
      "name"
    ]
  ],
  [
    "restaurantsById",
    [
      4275,
      85456,
      102474,
      105498,
      108642
    ],
    [
      "cuisine",
      "neighbourhood"
    ],
    "name"
  ],
  [
    "restaurantsById",
    [
      4275,
      85456,
      102474,
      105498,
      108642
    ],
    "priceBand",
    "id"
  ],
  [
    "restaurantsById",
    [
      4275,
      85456,
      102474,
      105498,
      108642
    ],
    "reviewSummary",
    [
      "count",
      "rating"
    ]
  ]
]
```

// cc @nickbalestra @chriscartlidge

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

this will fix #22 

this will fix #21 

in order to properly handle an array of arrays we need to spread `...` before calling the `.get()` method against the Falcor model

screen shot 2016-11-08 at 10 44 43

`falcorGet()` has also been removed from `componentDidMount()` as there is no need to fetch data w/o a proper query

in this PR there is also a little update at the template level that now is surfacing the version number in the title

### CODE REVIEW

**Comment by mattiaerre** [comment]
are you able to have a look at this PR @nickbalestra and/or @chriscartlidge ? I would like to publish this version ASAP as @ajcw is going to publish our OT blog post 😉

**Comment by nickbalestra** [comment]
Lgtm 💅

**Comment by mattiaerre** [comment]
ty @nickbalestra I am going to publish the v1.2.0 release

// cc @chriscartlidge

**Comment by chriscartlidge** [comment]
👍

**Pull request merged**
